### ISSUE TITLE
scandinavian empire

### ISSUE THREAD

**Issue by Yanosh6** [MiltonStanley/Quandrax#13]
Not sure if this is an issue, or working as intended, but my Scandinavian empire converted to kingdom of Scandinavia (and I don't have "adopt imperial administration" option). Also I was the only protestant country in EU3, and I was catholic in CK2.

**Comment by MiltonStanley** [comment]
The conversion for titles -> tags is pretty dumb at this point - with about 1200 titles, but only 200 tags, there's a lot of simplifications that have to be made without actually releasing a full-blown mod that models every possible title/country (which is my long-term goal).

Version 1 doesn't currently convert religion - it uses the default that exists in EU3. Version 2 (in development) will support religion.

I'd hate to label it "working as intended" - "enhancement available with next version" would be more accurate?

**Comment by Yanosh6** [comment]
It's good to know these issues will be addressed in next version. If I spot anything else that looks like bug I'll notify you :)

And thanks for making this Quandrax. It actually works very good for me, even with some small issues :)

**Comment by MiltonStanley** [comment]
Glad it _generally_ works!

**Comment by MiltonStanley** [comment]
It's not a true bug, but rather an inherent limitation in the converter.

After reviewing game code, I'm somewhat stuck on this. The problem is inherent to a converter - I'm stuck with Paradox's hardcoded values on certain things. As an example:

You create the Empire of Britannia in CK2. What should the convert to? Obviously, Great Britain.

The problem? E_Britannia is catholic, but GBR is Protestant. I can't change the hardcoded values that nations have.

The only solution is either to not convert it (but leave it as England, etc.), or look into a console command to change religion on the user end.

**Comment by MiltonStanley** [comment]
Well, 3 weeks later I've realized my previous statement is incorrect. It's trivially easy to ensure the correct religion is used. It's stored in the nation object in the 'religion' variable. If the file doesn't contain the nation object, it uses the default. By providing it, I should be able to bypass the default and have the correct settings.
